export const ACTIVIDADES =
    [
        {
        ID: '1',
        Titulo: 'La escondida de los colores: Un, dos, tres ¡te pillé! de Claudio y Pati Aguilera',
        Fecha: '7/9/2020',
        Curso:'Prekinder/Kinder',
        Materia:'',
        DescripcionVideo: 'Es importante leer diferentes relatos y preguntarle a tu hijo por sus preferencias respecto a personajes, lugares o partes del relato, ya que promueve el fomento lector y su lenguaje verbal. ',                    
        Video: undefined,
        DescripcionActividad: 'Lee y muestra el cuento “Un dos tres, te pillé”  a tu hijo/a, poniendo atención en los colores y  figuras. Después, pídele que dibuje su personaje o parte favorita de la historia. Haga clic en el enlace para leer el cuento: http://www.crececontigo.gob.cl/wp-content/uploads/2017/12/un-dos-tres.pdf',
        ActividadPDF: 'https://firebasestorage.googleapis.com/v0/b/app-mobile-meaning.appspot.com/o/Actividades%2FActividad%201.pdf?alt=media&token=e224ccb9-6016-4084-a27c-5a7b98b2bceb',
        },
        {
        ID: '2',
        Titulo: 'Presentando mi tema favorito',
        Fecha: '9/9/2020',
        Curso:'Prekinder/Kinder',
        Materia:'',
        DescripcionVideo: 'Una de las formas de promover la expresión oral de tu hijo es la realización de presentaciones simples, relacionadas en temas de su interés. Por ejemplo, su animal o personaje favorito. ',                    
        Video: undefined,
        DescripcionActividad: 'Pregúntale a tu hijo qué animal, personaje, etc. le gusta, planifica y graba una pequeña presentación oral en la que exponga su tema. Te invitamos a compartir este video con la familia y si quieres, con nuestro grupo.',
        ActividadPDF: 'https://firebasestorage.googleapis.com/v0/b/app-mobile-meaning.appspot.com/o/Actividades%2FActividad%202.pdf?alt=media&token=0da6d6e7-c45e-4daa-8439-a15876756934',
        },
        {
        ID: '3',
        Titulo: 'La música que bailo yo',
        Fecha: '11/9/2020',
        Curso:'Prekinder/Kinder',
        Materia:'',
        DescripcionVideo:'La música promueve el movimiento corporal de tu hijo/a a través de los diferentes ritmos. Es importante que él/ella opine e indique sus pasos favoritos para bailar estas canciones. ',                    
        Video: undefined,
        DescripcionActividad: 'Pídele a tu hijo/a que arme una lista en la que recomiende canciones y pasos de baile a alguien de su edad, considerando  sus propias preferencias musicales.',
        ActividadPDF: 'https://firebasestorage.googleapis.com/v0/b/app-mobile-meaning.appspot.com/o/Actividades%2FActividad%203.pdf?alt=media&token=2671954e-8ef3-4883-8b50-1a59150a7ea0',
        },
        {
        ID: '4',
        Titulo: 'Mi creación de figura humana',
        Fecha: '14/9/2020',
        Curso:'Prekinder/Kinder',
        Materia:'',
        DescripcionVideo:'Promover que tu hijo represente la figura humana a través de diferentes materiales fomenta su lenguaje artístico y su creatividad. También lo ayude a identificar y ser consciente de su propio cuerpo. ',                    
        Video: undefined,
        DescripcionActividad: 'Invita a tu hijo/a a construir libremente su propia figura humana con materiales naturales y reciclados en una hoja de papel. Ayúdalo en el proceso y felicítalo. ',
        ActividadPDF: 'https://firebasestorage.googleapis.com/v0/b/app-mobile-meaning.appspot.com/o/Actividades%2FActividad%204.pdf?alt=media&token=864a39da-86ce-4e90-af2a-42c80b6f337a',
        },
        {
        ID: '5',
        Titulo: 'Salto y cuento hasta 10',
        Fecha: '16/9/2020',
        Curso:'Prekinder/Kinder',
        Materia:'',
        DescripcionVideo:'¡Contemos de forma entretenida! Piensa en diferentes momentos del día en el que tu hijo/a pueda contar del 1 al 10 a través de movimientos corporales, ya sea saltando, jugando o moviéndose. ',                    
        Video: undefined,
        DescripcionActividad: 'Con Masking tape, arma una línea con los números del 1 al 10 en el suelo para que tu hijo pueda saltar y contar. Dile un número y pídele que llegue hasta él.',
        ActividadPDF: 'https://firebasestorage.googleapis.com/v0/b/app-mobile-meaning.appspot.com/o/Actividades%2FActividad%205.pdf?alt=media&token=f1de8f2a-7baa-47f9-a6a4-fea9ea68453c',
        },
        {
        ID: '6',
        Titulo: 'La travesía',
        Fecha: '21/9/2020',
        Curso:'Prekinder/Kinder',
        Materia:'',
        DescripcionVideo:'Motiva y promueve  que tu hijo/a refuerce su orientación espacial comunicando la posición de los objetos a través de diferentes categorías de ubicación, tal como como arriba/abajo, adentro/afuera, entre otras.',                    
        Video: undefined,
        DescripcionActividad: 'Te invitamos a jugar a “la travesía” con tu hijo/a en un pasillo de tu casa. Con esta actividad reforzaremos las matemáticas a través de las nociones espaciales. Descarga la guía para facilitar la realización de la actividad.',
        ActividadPDF: 'https://firebasestorage.googleapis.com/v0/b/app-mobile-meaning.appspot.com/o/Actividades%2FActividad%206.pdf?alt=media&token=adf4fce3-2f84-403d-9b32-6aac96b8ad77',
        },
        {
        ID: '7',
        Titulo: 'Intercambio de roles',
        Fecha: '23/9/2020',
        Curso:'Prekinder/Kinder',
        Materia:'',
        DescripcionVideo:'El juego sociodramático “cambio de roles” permite que tu hijo/a reconozca el rol que él/ella y los otros tienen dentro de la familia, fomentando su identidad personal. ',                    
        Video: undefined,
        DescripcionActividad: 'En familia, jueguen a personificar a otro integrante. Cada uno deberá hablar y actuar como la otra persona. Finalmente, conversen y compartan sus experiencias haciendo énfasis en las características de cada uno.',
        ActividadPDF: 'https://firebasestorage.googleapis.com/v0/b/app-mobile-meaning.appspot.com/o/Actividades%2FActividad%207.pdf?alt=media&token=f009343e-168a-445d-870f-3bed06d08ecd',
        },
        {
        ID: '8',
        Titulo: 'Chef: El plato favorito',
        Fecha: '25/9/2020',
        Curso:'Prekinder/Kinder',
        Materia:'',
        DescripcionVideo:'¡Cocina junto a tu hijo/a! Invita a que él/ella te ayude en la cocina en labores simples. Así, puedes reforzar distintas normas y promover su alimentación saludable. Finalmente, podrás conocer sus gustos, fomentando también su expresión oral.',                    
        Video: undefined,
        DescripcionActividad: 'Invita a tu hijo a cocinar cuidadosamente su plato favorito contigo. Indícale el paso a paso y los ingredientes en todo el proceso. Luego, compartan la preparación en familia, felicitando al niño/a por su gran trabajo en equipo. ',
        ActividadPDF: 'https://firebasestorage.googleapis.com/v0/b/app-mobile-meaning.appspot.com/o/Actividades%2FActividad%208.pdf?alt=media&token=9c1187af-aa5a-4111-a1bf-c1fd8dd1a1c9',
        },
        {
        ID: '9',
        Titulo: 'Experimentando con hielo',
        Fecha: '28/9/2020',
        Curso:'Prekinder/Kinder',
        Materia:'',
        DescripcionVideo:'Promueve que tu hijo participe en investigaciones científicas simples, tales como la observación de los cambios de estado del agua. Acompáñalo y explícale los fenómenos. ',                    
        Video: undefined,
        DescripcionActividad: 'Reúne 3 cubos de hielo y experimenta con tu hijo/a: 1. Expone un cubo al sol y observa lo que sucede. 2. Agrega sal a otro cubo y observa lo que sucede. 3.Inserta el último cubo en un vaso de agua y observa lo que sucede. Finalmente, comparen los diferentes procesos.',
        ActividadPDF: 'https://firebasestorage.googleapis.com/v0/b/app-mobile-meaning.appspot.com/o/Actividades%2FActividad%209.pdf?alt=media&token=4fb580a2-363f-41a0-bf58-5187431a9416',
        },
        {
        ID: '10',
        Titulo: 'Semejanzas y diferencias',
        Fecha: '2/10/2020',
        Curso:'Prekinder/Kinder',
        Materia:'',
        DescripcionVideo:'Comentarle a tu hijo que existe diversidad en las personas, indicando semejanzas y diferencias entre ellas, permite que comprenda que todos somos únicos e irrepetibles. ',                    
        Video: undefined,
        DescripcionActividad: 'Pídele a tu hijo/a que diga semejanzas y diferencias entre una dupla familiar: dos integrantes distintos o él y otro integrante. Registra sus comentarios en una bitácora. ',
        ActividadPDF: 'https://firebasestorage.googleapis.com/v0/b/app-mobile-meaning.appspot.com/o/Actividades%2FActividad%2010.pdf?alt=media&token=56ebb1bb-e3d7-475e-b5f7-cb1f60dc4011',
        }
    ];