export const TIPS =
    [
        {
        ID: '1',
        Titulo: 'Titulo Tip 1',
        Fecha: '1/10/2020',
        Curso:'Básica',
        DescripcionVideo: 'Aqui va la introducción al video.',                    
        Video: undefined,
        DescripcionActividad: 'Aqui va la actividad principal e introduccion al imprimible.',
        ActividadPDF: undefined,
        },
        {
        ID: '2',
        Titulo: 'Titulo Tip 2',
        Fecha: '2/10/2020',
        Curso:'Básica',
        DescripcionVideo: 'Aqui va la introducción al video.',                    
        Video: undefined,
        DescripcionActividad: 'Aqui va la actividad principal e introduccion al imprimible.',
        ActividadPDF: undefined,
        },
        {
        ID: '3',
        Titulo: 'Titulo Tip 3',
        Fecha: '3/10/2020',
        Curso:'Jardín',
        DescripcionVideo: 'Aqui va la introducción al video.',                    
        Video: undefined,
        DescripcionActividad: 'Aqui va la actividad principal e introduccion al imprimible.',
        ActividadPDF: undefined,
        },
        {
        ID: '4',
        Titulo: 'Titulo Tip 4',
        Fecha: '4/10/2020',
        Curso:'Jardín',
        DescripcionVideo: 'Aqui va la introducción al video.',                    
        Video: undefined,
        DescripcionActividad: 'Aqui va la actividad principal e introduccion al imprimible.',
        ActividadPDF: undefined,
        },
        {
        ID: '5',
        Titulo: 'Titulo Tip 5',
        Fecha: '5/10/2020',
        Curso:'Padres Primerizos',
        DescripcionVideo: 'Aqui va la introducción al video.',                    
        Video: undefined,
        DescripcionActividad: 'Aqui va la actividad principal e introduccion al imprimible.',
        ActividadPDF: undefined,
        },
    ];