export const TIPS =
    [    
        {
        ID: '1',
        Titulo: 'Tip 1',
        Fecha: '8/9/2020',
        Curso:'Prekinder/Kinder',
        DescripcionVideo: 'Hoy martes los invitamos a compartir ideas y actividades con el resto de la comunidad. A nosotros nos gusta este cuento para seguir identificando preferencias de tu hijo respecto a personajes, lugares o partes del relato. https://www.bpdigital.cl/info/1-2-3--00011384',              
        DescripcionActividad: '¿Qué cuentos les gustan a ustedes? ¿Conocen alguno donde también se puedan trabajar los números?',
        },
        {
        ID: '2',
        Titulo: 'Tip 2',
        Fecha: '10/9/2020',
        Curso:'Prekinder/Kinder',
        DescripcionVideo: 'Hoy los invitamos a seguir trabajando la expresión oral de sus hijos ¿Cómo han motivado a sus hijos para realizar presentaciones orales? Aquí les dejamos como ejemplo un video viral donde un estudiante chileno presenta un tema que lo identifica y le interesa: https://www.youtube.com/watch?v=jYWe9yAbLmA',                    
        DescripcionActividad: 'Aqui podria ir un text box para que respondan algo o manden feedback',
        },
        {
        ID: '3',
        Titulo: 'Tip 3',
        Fecha: '15/9/2020',
        Curso:'Prekinder/Kinder',
        DescripcionVideo: '¡Hola! Hoy sigamos promoviendo que el estudiante represente, identifique y sea consciente de la figura humana ¿Conocen juegos donde se refuerce el identificar las partes del cuerpo? Los invitamos a jugar a “Simón Dice”, incluyendo en cada instrucción alguna parte del cuerpo. Por ejemplo: “Simón dice: que te toques la nariz” ',                    
        DescripcionActividad: 'Aqui va la actividad principal e introduccion al imprimible.',
        },
        {
        ID: '4',
        Titulo: 'Tip 4',
        Fecha: '17/10/2020',
        Curso:'Prekinder/Kinder',
        DescripcionVideo: 'Hoy seguiremos reforzando el conteo del 1 al 10 combinado con movimientos corporales. ¡A  nosotros nos gusta jugar al luche! Como en este video https://www.instagram.com/p/B-keWwoB4vR/?utm_source=ig_web_copy_link',                   
        DescripcionActividad: 'Mañana no enviaremos actividades por las fiestas patrias…. Aunque siempre pueden contar cada intento que hagan en cualquier juego chileno. ¿Qué otros juegos conoces? ¡Comparte con los demás!',                    
        },
        {
        ID: '5',
        Titulo: 'Tip 5',
        Fecha: '22/9/2020',
        Curso:'Prekinder/Kinder',
        DescripcionVideo: '¡Hola papás! Hoy seguiremos reforzando el conteo del 1 al 10 y las nociones espaciales, combinado con movimientos corporales. ¡A  nosotros nos gusta jugar al luche! Como en este video: https://www.instagram.com/p/B-keWwoB4vR/?utm_source=ig_web_copy_link',        
        DescripcionActividad: '¿Qué otros juegos se les ocurren a ustedes?',
        },
        {
        ID: '6',
        Titulo: 'Tip 6',
        Fecha: '24/9/2020',
        Curso:'Prekinder/Kinder',
        DescripcionVideo: '¡Hola! Hoy seguiremos reforzando la identidad personal del niño/a.Pregúntale a tu hijo/a: ¿Qué quieres ser cuando seas grande? ¿Por qué? ¡Conversen sobre estos temas! Te dejamos un video para apoyar la reflexión: https://www.youtube.com/watch?v=01CzjpFtYI4',        
        DescripcionActividad: '¿Qué otros videos o cuentos tocan estos temas? ¡Compártelos!',
        },
    ];